export const liveChatMock = [
    { id: 1, name: "Imesha Dewmin", text: "This is awesome 🔥" },
    { id: 2, name: "Nimal Perera", text: "React makes UI so easy" },
    { id: 3, name: "Sarah Johnson", text: "Live chat UI is cool 👀" },
    { id: 4, name: "David Kim", text: "Can we add auto scroll?" },
    { id: 5, name: "Kavindu Silva", text: "This feels like YouTube live chat" },
    { id: 6, name: "John Doe", text: "Hello everyone 👋" },
    { id: 7, name: "Emily Clark", text: "Nice project!" },
    { id: 8, name: "Raj Malhotra", text: "Frontend is fun when it works 😄" },
    { id: 9, name: "Samantha Lee", text: "Redux makes state management clean" },
    { id: 10, name: "Michael Brown", text: "How do we scale this?" },

    { id: 11, name: "Chris Evans", text: "Looks smooth!" },
    { id: 12, name: "Ayesha Khan", text: "I love React hooks ❤️" },
    { id: 13, name: "Daniel Silva", text: "Great UI design" },
    { id: 14, name: "Priya Sharma", text: "Can we connect WebSockets?" },
    { id: 15, name: "Liam Wilson", text: "This is addictive 😂" },
    { id: 16, name: "Olivia Martin", text: "Very clean code structure" },
    { id: 17, name: "Ethan Wright", text: "Learning a lot here" },
    { id: 18, name: "Isuru Perera", text: "Sri Lanka devs unite 🇱🇰" },
    { id: 19, name: "Noah Taylor", text: "Auto update feature would be 🔥" },
    { id: 20, name: "Mia Anderson", text: "This looks like production app" },

    { id: 21, name: "Arjun Nair", text: "Keep going!" },
    { id: 22, name: "Sophia Thomas", text: "Nice animations would help" },
    { id: 23, name: "Benjamin Scott", text: "What about performance?" },
    { id: 24, name: "Zara Ali", text: "Frontend dev journey 🚀" },
    { id: 25, name: "James Hall", text: "Looks very responsive" },
    { id: 26, name: "Fatima Noor", text: "I like this architecture" },
    { id: 27, name: "Lucas Garcia", text: "Add emojis support 😎" },
    { id: 28, name: "Harper Young", text: "Smooth scrolling needed" },
    { id: 29, name: "Ravi Fernando", text: "Good job bro 👏" },
    { id: 30, name: "Emma White", text: "This is next level UI" },

    { id: 31, name: "Henry Adams", text: "Streaming feels real-time 🔴" },
    { id: 32, name: "Ella Baker", text: "Love this implementation" },
    { id: 33, name: "William Clark", text: "Redux toolkit is powerful" },
    { id: 34, name: "Chamara Jay", text: "Nice work on state updates" },
    { id: 35, name: "Grace Hall", text: "UI is very clean" },
    { id: 36, name: "Jack Miller", text: "Can we add timestamps?" },
    { id: 37, name: "Amelia Scott", text: "Feels like Twitch chat" },
    { id: 38, name: "Owen Harris", text: "Performance is key ⚡" },
    { id: 39, name: "Aiden Moore", text: "This is fun to build" },
    { id: 40, name: "Sophia Wilson", text: "Good spacing and layout" },

    { id: 41, name: "Logan Thomas", text: "Auto scroll would be great" },
    { id: 42, name: "Isuru Bandara", text: "Sri Lankan dev power 💪" },
    { id: 43, name: "Mason Lee", text: "Frontend mastery" },
    { id: 44, name: "Lily Johnson", text: "Nice UX flow" },
    { id: 45, name: "Jacob Martin", text: "State updates are smooth" },
    { id: 46, name: "Sophie Brown", text: "Very intuitive design" },
    { id: 47, name: "David Wilson", text: "Looks production ready" },
    { id: 48, name: "Chloe Davis", text: "Can we add reactions?" },
    { id: 49, name: "Matthew Garcia", text: "Good job on this project" },
    { id: 50, name: "Ella Martinez", text: "This is impressive 🔥" },

    { id: 51, name: "Ryan Anderson", text: "Clean component structure" },
    { id: 52, name: "Emily Thomas", text: "Love the responsiveness" },
    { id: 53, name: "Daniel White", text: "Redux makes it scalable" },
    { id: 54, name: "Ava Harris", text: "Very smooth UI transitions" },
    { id: 55, name: "James Clark", text: "Can we optimize renders?" },
    { id: 56, name: "Isuru Perera", text: "Another SL dev here 🇱🇰" },
    { id: 57, name: "Benjamin Young", text: "Nice architecture choice" },
    { id: 58, name: "Mia Scott", text: "Feels very modern" },
    { id: 59, name: "Lucas King", text: "Add dark mode 🌙" },
    { id: 60, name: "Harper Lewis", text: "Great attention to detail" },

    { id: 61, name: "Ethan Walker", text: "This is addictive to build" },
    { id: 62, name: "Amelia Hall", text: "Real-time vibe 🔥" },
    { id: 63, name: "Logan Allen", text: "Nice state flow" },
    { id: 64, name: "Charlotte Wright", text: "Very clean UI/UX" },
    { id: 65, name: "Henry Scott", text: "Good job team!" },
    { id: 66, name: "Ella Green", text: "Smooth experience" },
    { id: 67, name: "Jack Adams", text: "Impressive work" },
    { id: 68, name: "Aiden Baker", text: "Can scale easily 👍" },
    { id: 69, name: "Sophia Nelson", text: "Looks professional" },
    { id: 70, name: "William Carter", text: "Nice real-time feel" },

    { id: 71, name: "Olivia Mitchell", text: "Good performance handling" },
    { id: 72, name: "James Perez", text: "Redux slice is clean" },
    { id: 73, name: "Emma Roberts", text: "UI is very polished" },
    { id: 74, name: "Noah Turner", text: "Auto updates working well" },
    { id: 75, name: "Ava Phillips", text: "Love this chat system" },
    { id: 76, name: "Liam Campbell", text: "Very scalable design" },
    { id: 77, name: "Isuru Fernando", text: "SL dev checking in 🇱🇰" },
    { id: 78, name: "Mason Rivera", text: "Nice optimization ideas" },
    { id: 79, name: "Sophia Cooper", text: "Feels like real app" },
    { id: 80, name: "Ethan Reed", text: "Great work overall" },

    { id: 81, name: "Chloe Morgan", text: "Smooth UX flow 👌" },
    { id: 82, name: "Daniel Murphy", text: "Good real-time logic" },
    { id: 83, name: "Mia Bell", text: "Very clean architecture" },
    { id: 84, name: "Jack Bailey", text: "Nice React usage" },
    { id: 85, name: "Ella Rivera", text: "Impressive UI build" },
    { id: 86, name: "Lucas Cox", text: "Can handle more users?" },
    { id: 87, name: "Harper Diaz", text: "Looks production level" },
    { id: 88, name: "Benjamin Wood", text: "Redux is doing heavy lifting" },
    { id: 89, name: "Ava Ward", text: "Very smooth chat updates" },
    { id: 90, name: "James Flores", text: "Great project!" },

    { id: 91, name: "Olivia Simmons", text: "Auto scroll is essential" },
    { id: 92, name: "Ethan Price", text: "Nice scaling approach" },
    { id: 93, name: "Sophia Bennett", text: "Clean UI components" },
    { id: 94, name: "Noah Hughes", text: "Feels like YouTube live chat" },
    { id: 95, name: "Mia Long", text: "Very modern design" },
    { id: 96, name: "Liam Patterson", text: "Good structure overall" },
    { id: 97, name: "Ava Ross", text: "Real-time updates 🔥" },
    { id: 98, name: "Lucas Gray", text: "Nice and responsive" },
    { id: 99, name: "Isuru Jay", text: "SL devs everywhere 🇱🇰" },
    { id: 100, name: "Emma Watson", text: "This is next level 🚀" }
];